human:
  baidu:
    api-key:
    secret-key:
  aliyun:
    access-key-id:
    access-key-secret:
  chat:
    api-key:
    base-url: https://qianfan.baidubce.com/v2
    models:
      - title: DeepSeek-V3
        value: deepseek-v3
      - title: DeepSeek-R1
        value: deepseek-r1

spring:
  ai:
    openai:
      api-key:
      chat:
        base-url: https://qianfan.baidubce.com
        completions-path: /v2/chat/completions
        options:
          model: deepseek-v3.2

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: 123456

logging:
  level:
    web.digital.human: info
  file:
    name: logs/web-digital-human.log