human:
  baidu:
    api-key:
    secret-key:
    qianfan:
      api-key:
      access-key:
      secret-key:
  alibaba:
    aliyun:
      access-key-id:
      access-key-secret:
  openai:
    base-url: https://api.deepseek.com
    api-key:

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: 123456