human:
  baidu:
    api-key:
    secret-key:
  aliyun:
    access-key-id:
    access-key-secret:
  chat:
    api-key:
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    models:
      - title: DeepSeek-V3.2
        value: deepseek-v3.2

spring:
  ai:
    openai:
      api-key:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        completions-path: /v1/chat/completions
        options:
          model: deepseek-v3.2
      embedding:
        embeddings-path: /v1/embeddings
        options:
          model: text-embedding-v4

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: 123456

logging:
  level:
    web.digital.human: info
    org.springframework.ai: debug
  file:
    name: logs/web-digital-human.log